#!/usr/bin/env bash
set -e

function req {
	local program="$1"

	if [[ -z "$(which "$program")" ]];
	then
		echo "$program is required" >&2
		exit 1
	fi
}

req python3
req virtualenv
req pip


MICEMD_VENV="${BASH_SOURCE%/*}/.micemd-virtualenv"

[[ -d "$MICEMD_VENV" ]] || NEEDS_INSTALLATION="true"

if [[ "$NEEDS_INSTALLATION" == "true" ]];
then
	# Create new virtualenv directory.
	virtualenv --python=python3 --no-site-packages "${MICEMD_VENV}"

	# Just an empty line to group output lines.
	echo
fi

# Deactivate virtual environment before exiting script.
trap deactivate EXIT;

# Activate virtual environment.
source "${MICEMD_VENV}/bin/activate"

if [[ "$NEEDS_INSTALLATION" == "true" ]];
then
	# Install python packages/dependencies.
	pip install --no-deps --requirement requirements.txt

	# Just an empty line to group output lines.
	echo
fi

# Start.
python -i "${BASH_SOURCE%/*}/mice.py" "$@"
